### ISSUE TITLE
Scroll is disabled in Table view when in Expanded view

### ISSUE THREAD

**Issue by joe-fagan** [bitnine-oss/AGViewer#11]
**Description**
Scroll is disabled in Table view when in Expanded view. Unable to go to bottom or choose next or previous.

**To Reproduce**
In a graph with more than a few edges 

`match p=()-[*]-() return p limit 100;`

Then choose Table view, scroll to bottom and choose 20/page
Then go to expanded view.
Scroll is disabled

**Expected behaviour**
Scroll works

**Desktop (please complete the following information):**
 - OS:  Win 10
 - Browser Chrome
 - Version 89.0.4389.128 (Official Build) (64-bit)

**Comment by emotionbug** [comment]
@shinhanbyeol 
OK. We will fix it until next week.

**Comment by emotionbug** [comment]
On latest builds, it will be fixed.
