### ISSUE TITLE
"Unexpected token : in JSON at position 76" when querying a path in AGE

### ISSUE THREAD

**Issue by audiBookning** [bitnine-oss/AGViewer#12]
**Describe the bug**
When querying a path 
```sql
SELECT * from cypher('my_graph_name', $$
  MATCH p=(a)-[]-(b)
  RETURN p
$$) as (a agtype);
```
i get the error: "Unexpected token : in JSON at position 76" 

**To Reproduce**
I created a docker compose file to test AGViewer with AGE. I used both the images of AGViewer and sorrell/agensgraph-extension in it.
The files and the specific steps that i used can be seen in this repo [https://github.com/audiBookning/Compose-AGE-AGViewer](https://github.com/audiBookning/Compose-AGE-AGViewer).
But they can be resumed:
- create some nodes
- create some relation between two of them
- try to query the path of those two
- get the error "Unexpected token : in JSON at position ***"

**Expected behavior**
The query should give the nodes and relations between them.
I tried the path query directly in the psql cli and there was no problem.
I don't know if this issue really belongs here or it belongs on the AGE repo.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by shinhanbyeol** [comment]
I checked the issue.

We will proceed to check the cause.
I will answer after solving the issue.

**Comment by emotionbug** [comment]
@audiBookning  fixed this issue.
try again.

**Comment by audiBookning** [comment]
Nice!
I just tried the steps on my side and there was no problems.
When i have more time, i will try to test AGE and AGViewer more.
In the mean time i will close this issue
Thanks.

**Comment by emotionbug** [comment]
@audiBookning
we are great thanks to your reporting.
