### ISSUE TITLE
Problem with applying edge weight

### ISSUE THREAD

**Issue by jbiz805** [bitnine-oss/AGViewer#19]
Upon playing around with AG Viewer, I think i may have found a bug.

It's regarding the seemingly newly added "Apply Edge Weight" feature.
When I execute edge and properties label, the apply edge weight feature seems to work just fine, however, in a node label, I can't seem to apply edge weight there.
(refer to the image below)
![image](https://user-images.githubusercontent.com/49049733/120611155-d69dd480-c48e-11eb-8741-91c13a521abd.png)

I'm not sure if this is a bug or it is as intended, but it would be convenient to have this feature included in the node label as well.

The files I used for the test are from this blog:  https://bitnine.net/blog-agens-solution/ag-cloud/how-to-import-csv-in-ag-cloud-express/

**Comment by shinhanbyeol** [comment]
Thank you for bug reporting. 😊
 
We will actively review the function of weighting nodes.
