### ISSUE TITLE
Understanding Graph Database and Cypher Dataset currently not working in AGViewer

### ISSUE THREAD

**Issue by jbiz805** [bitnine-oss/AGViewer#21]
**Describe the bug**
AGViewer is not showing one of the four datasets available: Understanding Graph Database and Cypher

**To Reproduce**
1. Go to Add New Project
2. Click on Understanding Graph & Cypher
3. Click Create New Project
4. Launch AGViewer

**Expected behavior**
See dataset in AGViewer, which currently is not available. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49049733/121145399-e136e000-c879-11eb-8abe-74655dd9f45f.png)
![image](https://user-images.githubusercontent.com/49049733/121145428-e98f1b00-c879-11eb-8ab4-156a0d6d50c2.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by Kim-Changhyun** [comment]
AG Cloud Express's "Understanding Graph & Cypher" creates an empty DB when creating a project.
Execute the create statement in the 4th tutorial and execute refresh.
You can see 2 nodes and 1 edge.
