### ISSUE TITLE
Error when trying to view a graph: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Uria1** [bitnine-oss/AGViewer#33]
**Description**
Whenever I try to view related nodes I get this error:
`Converting circular structure to JSON
--> starting at object with constructor 'Object'
--- property 'properties' closes the circle`

**Steps to Reproduce**
1. Create two related nodes. i.e. `create (n:engine)-[l:partOf]->(c:car)`
1. Click on a node label (i.e. "car")
2. A query is generated. i.e.: `SELECT * from cypher('graph1', $$
          MATCH (V:car)
          RETURN V
$$) as (V agtype);`
3. Click on the `Run Query` button
4. You get the above error

**Expected Behavior**
A graph with 2 nodes and a relation is displayed

**Desktop**
 - OS: Ubuntu
 - Browser: chrome 
 - Version: 91.0.4472.114 (Official Build) (64-bit)
 - Running on Docker version 20.10.7, build f0df350
 - Image: bitnine/agviewer:latest

**Additional Context**
It is possible to see single nodes, but not all of them. Any query with a relation fails with the above error.
i.e. `match (n)-[r]-(m) return r`
This issue does not reproduce with image `bitnine/agviewer:0.5.0`

**Comment by shinhanbyeol** [comment]
Thank you for the tip-off.
The issue was resolved by @emotionbug.

**Comment by emotionbug** [comment]
Will be fixed in latest tag.
